// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/chat/chat-chain': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/chat-chain.post').default>>>>
    }
    '/api/embeddings/convert': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/embeddings/convert.post').default>>>>
    }
    '/api/embeddings/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/embeddings/save.post').default>>>>
    }
    '/api/file/gen-chunk': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/file/gen-chunk.post').default>>>>
    }
    '/api/file/save-vector': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/file/save-vector.post').default>>>>
    }
    '/api/navigation/direction': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/navigation/direction.post').default>>>>
    }
    '/api/navigation/places': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/navigation/places.post').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/index').default>>>>
    }
  }
}
export {}